# In this notebook we are going to cover some of the most fundamental concepts of tensors using TensorFlow


More specifically we are going to cover:
* Intro to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors & NumPy


## Introduction to Tensors


In [1]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)



2.8.2


In [2]:
#create tensors with tf.constant()
scalar  = tf.constant(7.5)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=7.5>

In [3]:
# check the nr of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#check the dim of our vector
vector.ndim

1

In [6]:
# create a matrix that has more than 1 dim
matrix = tf.constant([[10,7], [12,3]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [12,  3]], dtype=int32)>

In [7]:
matrix.ndim


2

In [8]:
# create another matrix
another_matrix = tf.constant([[10.,2.,],[3.,4.],[7.,10.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  2.],
       [ 3.,  4.],
       [ 7., 10.]], dtype=float16)>

In [9]:
#check the ndim of another_matrix
another_matrix.ndim

2

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1,10,2],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                       [[13,14,15],
                        [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1, 10,  2],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

### Create tensors with `tf.variable`

In [12]:
# create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10,10])
unchangeable_tensor =  tf.constant([10,10])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [13]:
#changeable_tensor[0] = 4

#Let's try .assign() to change the first element of the vector
changeable_tensor[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([ 4, 10], dtype=int32)>

In [14]:
# Now let's try to change our unchangeable tensor
#unchangeable_tensor[0].assign(4)  --cannot change a constant object

### Creating random tensors
Random tensors are tensors of some arbitrary size with random numbers


In [15]:
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2  = random_2.normal(shape=(3,2))

#Are they equal
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements of a tensor

In [16]:
not_shuffled = tf.constant([[10,7],
                            [2,3],
                            [4,5]])

#not_shuffled

#shuffle our non_shuffled tensor
tf.random.set_seed(5)  # global random seed
tf.random.shuffle(not_shuffled, seed=12) #operational random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5],
       [ 2,  3]], dtype=int32)>

> Rule 4: if both of type of seeds are set than the tensors with be shuffled in the same order

### Other ways to make tensors


In [17]:
# Create a tensor of all ones
tensor_1 = tf.ones([10,7])
#tensor_1.ndim
tensor_1

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy array into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [19]:
# turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) #use capital for matrix or tensors
# y = tf.constant(vector) # use non-capital for vector

A = tf.constant(numpy_A)
A
B = tf.constant(numpy_A, shape=(3,2,4))
B
#the size of the shape must not exceed the number 24 elements = of 3*2*4
C = tf.constant(numpy_A,shape=(4,6))
B, C

(<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]],
 
        [[17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]], dtype=int32)>)

### Getting information from your tensors (tensor attributes)

Tensor attributes are:
- Shape
- Rank
- Axis or dim
- Size


In [20]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape =(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [22]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [23]:
2*3*4*5

120

In [24]:
# Get various attributes of our tensor
print("Data type of every element:= ", rank_4_tensor.dtype)
print("Number of dim (rank):= ",rank_4_tensor.ndim)
print("Shape of our tensor:= ",rank_4_tensor.shape)
print("Elements along the 0 axis:=", rank_4_tensor[0])
print("Elements along the last axis:=", rank_4_tensor[-1])
print("The size of the tensor:= ",tf.size(rank_4_tensor))
print("The size of the tensor:= ",tf.size(rank_4_tensor).numpy())

Data type of every element:=  <dtype: 'float32'>
Number of dim (rank):=  4
Shape of our tensor:=  (2, 3, 4, 5)
Elements along the 0 axis:= tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Elements along the last axis:= tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
The size of the tensor:=  tf.Tensor(120, shape=(), dtype=int32)
The size of the tensor:=  120


### Indexing tensors
Tensors can be indexed just like Python lists.

In [25]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [26]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [27]:
# Get the first element from each dimension from each index except for the last one
rank_4_tensor[:1,:1,:1,:]
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor
rank_2_tensor =tf.constant([[10,7], 
                           [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim


(TensorShape([2, 2]), 2)

In [29]:
some_list[-1]

4

In [30]:
#Get the last item of each row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [31]:
# Add an extra dim of our 2 rank tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [32]:
# Alternative to newaxis
tf.expand_dims(rank_2_tensor,axis=-1)#-1 expands the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
# Alternative to newaxis
tf.expand_dims(rank_2_tensor,axis=0)#0 expands the 0- axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (Tensors Operation)

**Basic Operations**
+,-,*,/

In [34]:
tensor = tf.constant([[10,7],
                      [3,4]])
#adding 
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [35]:
# multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [36]:
#substraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [37]:
# or use built-in math function
tf.multiply(tensor,10)
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix multiplication**
In ML matrix multiplication is one of the most common tensor operations

check matrixmultiplication.xyz for dotProduct op

In [38]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
# Matrix multiplication using Python '@' operation
tensor
tensor @ tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

**Exercise 1**


In [40]:
tensor_1 = tf.constant([[[1,2,5],
                         [7,2,1],
                         [3,3,3]]])

tensor_2 = tf.constant([[[3,5],
                         [6,7],
                         [1,8]]])

tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [41]:
X= tf.constant([[1,2],
                 [3,4],
                 [5,6]])

Y= tf.constant([[7,8],
                 [9,10],
                 [11,12]])
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [42]:
X @ tf.reshape(Y, shape=(2,3))

tf.matmul(X,tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [43]:
# Try to change the shape of X instead of Y
tf.matmul(tf.reshape(X, shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [44]:
# Transpose operation is different from reshape
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [45]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

**The dot product**
Matrix multiplication is also referred to as the dot product
You can perform matrix multiplication using 


*   tf.matmul()
*   tf.tensordot()

In [46]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [47]:
# Perform the dot product on X and Y (X or Y is required to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [48]:
# Perform matrix multiplication between X and Y(transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [49]:
# Perform matrix multiplication between X and Y(reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [50]:
# check Y, reshape Y and transpose Y
print ("Normal Y:")
print(Y, "\n")
print("Y reshaped to (2,3): ")
print(tf.reshape(Y, shape=(2,3)), "\n")
print("Y transposed: ")
print(tf.transpose(Y),"\n")

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



In [51]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

### Change the datatype of a tensor

In [52]:
# Create a new tensor with default data type
B = tf.constant([1.7,7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [53]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [54]:
# Change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [55]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [56]:
# change again
E_float_16 = tf.cast(E, dtype=tf.float16)
E_float_16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [57]:
# Get the absolute values
D = tf.constant([-1,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -1, -10], dtype=int32)>

In [58]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

Let's go through the following forms of aggreggation:


*   Get the maximum
*   Get the minimum
*   Get the mean
*   Get the sum of tensors

In [59]:
# Create a random tensor with values between 0 and 100 and size 50
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([23, 97, 94, 71, 30, 89, 92, 78, 42, 99, 23,  9, 11, 53, 56, 35, 73,
       96, 61, 55, 17, 93, 74, 32, 32, 91, 39, 66, 17, 56, 49, 41, 75, 46,
       96, 94,  2, 55, 91, 92, 10, 52, 77, 30, 35, 31, 27, 37, 92, 10])>

In [60]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [61]:
# Find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [62]:
# Find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [63]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=54>

In [64]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2746>

** Excerise: Find variance and standard deviation of E tensor**

In [65]:
# Find the variance of E tensor
#import tensorflow_probability as tfp
#tfp.stats.variance(E)
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=866.1136>

In [66]:
# Find the std of our tensor
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.429808>

### Find the index position of maximum and minimum

In [67]:
# Create a new tensor for finding the min and max index
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [68]:
# Find the index of the max element
tf.argmax(F)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [69]:
# Find the max value (element) of our tensor
F[tf.argmax(F)], tf.reduce_max(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [70]:
# check for equality between
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [71]:
# Find the index of min element
tf.argmin(F)


<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [72]:
# Find the min value (element) of our tensor
F[tf.argmin(F)], tf.reduce_min(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a tensor (removing all single dimensions)

In [73]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1,1,1,1,50))
G


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [74]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding tensors

In [75]:
# Create a list of indeces
some_list = [0,1,2,3] # could be red, green, blue, purple

# one hot encode our list of indices
tf.one_hot(some_list, depth = 4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [76]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="LLL", off_value="BBB")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'LLL', b'BBB', b'BBB', b'BBB'],
       [b'BBB', b'LLL', b'BBB', b'BBB'],
       [b'BBB', b'BBB', b'LLL', b'BBB'],
       [b'BBB', b'BBB', b'BBB', b'LLL']], dtype=object)>

### Squaring, log, square root

In [77]:
# create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [78]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [79]:
# square root
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [80]:
# Find the log 
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

In [81]:
# create a tensor directly from NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [82]:
# convert the tensor J to a numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [83]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

#check the data types of each (only the precision changes)
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU

In [84]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [85]:
!nvidia-smi

Thu Jun 30 14:26:17 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P0    29W /  70W |    266MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** If you have access to a CUDA-enabled GPU tensorflow will make use of it automatically whenever it's possible

### **Ex:00**

In [86]:
# create a scalar, vector, matrix and a tensor
scalar_1 = tf.constant(5.6)

vec_1 = tf.constant([2.4,3.6])

MAT_X = tf.constant([[3,4],
                     [0,7]])
T_X = tf.constant([[[1.2,3.5,2.01],
                     [3.8,6.5,4.1]],
                   [[2.09,1.32,5.1],
                    [2.05,8.54,7.01]],
                    [[1.04,8.24,9.5],
                     [4.01,8.24,2.5]]])

In [87]:
# Print properties of the above objects
print("Shape of scalar_1: ",scalar_1.shape)
print("Dim of scalar_1: ",scalar_1.ndim)
print("Size of scalar_1: ",tf.size(scalar_1))
print("\nShape of vec_1: ",vec_1.shape)
print("Dim of vec_1: ",vec_1.ndim)
print("Size of vec_1: ",tf.size(vec_1))
print("\nShape of MAT_X: ",MAT_X.shape)
print("Dim of MAT_X: ",MAT_X.ndim)
print("Size of MAT_X: ",tf.size(MAT_X))
print("\nShape of T_X: ",T_X.shape)
print("Dim of T_X: ",T_X.ndim)
print("Size of T_X: ",tf.size(T_X))


Shape of scalar_1:  ()
Dim of scalar_1:  0
Size of scalar_1:  tf.Tensor(1, shape=(), dtype=int32)

Shape of vec_1:  (2,)
Dim of vec_1:  1
Size of vec_1:  tf.Tensor(2, shape=(), dtype=int32)

Shape of MAT_X:  (2, 2)
Dim of MAT_X:  2
Size of MAT_X:  tf.Tensor(4, shape=(), dtype=int32)

Shape of T_X:  (3, 2, 3)
Dim of T_X:  3
Size of T_X:  tf.Tensor(18, shape=(), dtype=int32)


In [88]:
# Create two tensors with values between 0 and 1 with shape=[5, 300].

X = tf.random.uniform(minval=0, shape=[5,300])

Y = tf.random.uniform(minval=0, shape=[5,300])

X,Y

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
         0.2584542 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936

In [89]:
# Multiply the two tensors
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.71399 , 80.87825 , 78.3285  , 78.25969 , 79.13057 ],
       [70.12708 , 72.09945 , 70.16779 , 73.24609 , 74.27741 ],
       [75.16    , 79.52857 , 76.746445, 78.14266 , 77.286804],
       [77.11355 , 75.401215, 72.793785, 75.06638 , 75.206535],
       [79.87285 , 83.40138 , 78.57372 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [95]:
# Multiply the two tensors
tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.71399 , 80.87825 , 78.3285  , 78.25969 , 79.13057 ],
       [70.12708 , 72.09945 , 70.16779 , 73.24609 , 74.27741 ],
       [75.16    , 79.52857 , 76.746445, 78.14266 , 77.286804],
       [77.11355 , 75.401215, 72.793785, 75.06638 , 75.206535],
       [79.87285 , 83.40138 , 78.57372 , 79.025894, 81.82093 ]],
      dtype=float32)>

In [90]:
# Create a radom tensors with values between 0 and 1 and shape=...
Z = tf.random.uniform(minval=0, shape=[224, 224, 3])
Z

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
        [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
        [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
        ...,
        [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
        [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
        [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

       [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
        [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
        [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
        ...,
        [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
        [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
        [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

       [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
        [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
        [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
        ...,
        [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],
        [3.3173549e-01

In [102]:
#find the min and max along the first axis
min = tf.reduce_min(Z)
print(f'The minimum value is: {min}')

max = tf.reduce_max(Z)
print(f'The max value is: {max}')

The minimum value is: 1.0967254638671875e-05
The max value is: 0.9999902248382568


In [103]:
# Create a random tensor with shape [1, 224, 224, 3] and then squeeze it

W = tf.random.Generator.from_seed(42)

unsqueezed_W = W.normal(shape=(1,244,244,3))
print("Shape before squeezing: ",tf.shape(unsqueezed_W))

Shape before squeezing:  tf.Tensor([  1 244 244   3], shape=(4,), dtype=int32)


In [105]:
# Squeeze the tensor
squeezed_W = tf.squeeze(unsqueezed_W)
print("Shape after squeezing: ",tf.shape(squeezed_W))

Shape after squeezing:  tf.Tensor([244 244   3], shape=(3,), dtype=int32)


In [106]:
# create a tensor with shape(10)
tensor_10 = tf.constant([4,8,12,-89,3,2,4,7,11,10])

#find the index with max value
index_max = tf.argmax(tensor_10)
print("The index with max value:",index_max)
print("The value of the max index of the tensor: ",tensor_10[index_max])


The index with max value: tf.Tensor(2, shape=(), dtype=int64)
The value of the max index of the tensor:  tf.Tensor(12, shape=(), dtype=int32)


In [108]:
# Create a one-hot encoded of the above tensor
one_hot_encoded = tf.one_hot(tensor_10, depth=10)
one_hot_encoded

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>